### ISSUE TITLE
cannot save the image

### ISSUE THREAD

**Issue by Mafti** [KoBeWi/Godot-Spritesheet-Generator#1] opened 2021-12-11 13:41 UTC
Hi,

Besides the [?] not clickable, I am trying to save the image.
but i get keeping the error: 

E 0:01:11.322   save_image: Can't save PNG at path: '//foo.png'.
  <C++ Error>   Condition "err" is true. Returned: err
  <C++ Source>  drivers/png/resource_saver_png.cpp:56 @ save_image()
  <Stack Trace> SpritesheetGenerator.tscn::1:255 @ save_png()

I am using it on a windows machine :)

**Comment by KoBeWi** [comment] 2021-12-11 13:45
The [?] is not supposed to be clickable, it shows a tooltip when hovered. Not sure how to improve it.

I'll look into the error.

**Comment by Mafti** [comment] 2021-12-11 13:57
Oh, extra information, i am dragging images from windows explorer, not via godot itself..

**Comment by KoBeWi** [comment] 2021-12-11 14:05
I can't reproduce this error. Where are your images located? What are the steps to reproduce the bug? Does it happen in other projects too?

> i am dragging images from windows explorer, not via godot itself..

This is the intended usage.

**Comment by Mafti** [comment] 2021-12-11 14:40
Hi,

It works fine when selecting a folder.
It does not work when opening the folder, select all images and drag/drop those.

**Comment by KoBeWi** [comment] 2021-12-11 14:41
Do you have the newest version from AssetLib? This bug was fixed already.

**Comment by Mafti** [comment] 2021-12-11 19:40
I have, installed it today .. weird

**Comment by KoBeWi** [comment] 2021-12-11 19:43
Does any red error message appear?
I managed to reproduce the bug if the first image from directory is invalid.

**Comment by KoBeWi** [comment] 2021-12-24 16:11
Fixed in f9556c99fdd1386aac5a5142d0e6859514103e6c

**Closed as completed by KoBeWi** 2021-12-24 16:11 UTC
